name: Tag Documentation Release

on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:

    - name: Parse Event
      id: event
      run: |
        echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Release Tag
      id: tag
      uses: paketo-buildpacks/github-config/actions/tag/tag-docs-submodule@main
      with:
        version: ${{ steps.event.outputs.tag }}

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Create Docs Tag
      run: |
       git tag ${{ steps.tag.outputs.tag }}

    - name: Push
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: main
